### PR TITLE
fix error "false can't be coerced into Float"

### LINKED ISSUE #118: resource_lvm_logical_volume.rb library compilation error
### Cookbook version
4.0.4

### Chef-client version
12.17.44
### Platform Details
CentOS 6.8 running in AWS

### Scenario:
Chef-client convergence failure

### Steps to Reproduce:
We use the ephemeral-lvm from rightscale cookbook which depends on this cookbook to configure format and mount ephemeral drives as an LVM raid drive.

### Expected Result:
Drives to be configured and mounted.

### Actual Result:
Failure in the resource_lvm_logical_volume.rb library during compilation. This was working before we upgraded to the latest LVM release.

  Starting Chef Client, version 12.17.44
resolving cookbooks for run list: ["role-dse-aws-nativex"]
Synchronizing Cookbooks:
  - cron (3.0.0)
  - iptables (3.0.1)
  - lvm (4.0.4)
  - nfs (2.3.1)
  - timezone-ii (0.2.0)
  - ntp-nativex (1.1.0)
  - ohai (4.2.3)
  - nano (1.0.3)
  - role-base-linux-nativex (1.3.2)
  - yum-epel (2.1.0)
  - ohai-nativex (1.0.0)
  - chef-sugar (3.4.0)
  - motd (0.6.4)
  - hostsfile (2.4.5)
  - apt (5.0.1)
  - numad-nativex (0.1.0)
  - java (1.43.0)
  - logrotate (2.1.0)
  - seven_zip (2.0.2)
  - aws (4.1.3)
  - dse-nativex (1.1.1)
  - role-dse-aws-nativex (1.3.2)
  - mingw (1.2.4)
  - limits (1.0.0)
  - chef_handler (2.0.0)
  - collectd-ng (2.2.0)
  - timezone-nativex (1.0.0)
  - graphite-nativex (1.1.1)
  - vim (2.0.2)
  - bash-completion (0.1.0)
  - autofs-nativex (1.1.1)
  - sysctl (0.8.1)
  - auto-patch (0.1.10)
  - line (0.6.3)
  - mlocate-nativex (1.0.0)
  - snmp (4.0.0)
  - dstat (0.1.1)
  - ephemeral_lvm-nativex (1.0.1)
  - ssh-authorized-keys-nativex (1.0.0)
  - sshd (1.3.0)
  - windows (2.1.1)
  - ssh_authorized_keys (0.3.0)
  - ad-nativex (3.2.1)
  - autopatch-nativex (1.3.1)
  - spacewalk-nativex (1.1.0)
  - tuned-nativex (0.1.1)
  - solarwinds-nativex (1.2.0)
  - aws-tagging-nativex (1.1.1)
  - build-essential (7.0.3)
  - chef-client (7.0.3)
  - chef-client-updater-nativex (1.0.1)
  - sudo (3.1.0)
  - yum (4.1.0)
  - compat_resource (12.16.3)
  - ephemeral_lvm (1.0.17)
  - hostname-nativex (1.0.2)
  - postfix-nativex (1.0.0)
  - homebrew (3.0.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Recipe: aws::ec2_hints
  * ohai_hint[ec2] action create
    * directory[/etc/chef/ohai/hints] action create (up to date)
    * file[/etc/chef/ohai/hints/ec2.json] action create (up to date)
     (up to date)
Recipe: ohai-nativex::awsplugin
  * ohai_hint[aws] action create
    * directory[/etc/chef/ohai/hints] action create (up to date)
    * file[/etc/chef/ohai/hints/aws.json] action create (up to date)
     (up to date)
  * ohai_plugin[aws] action create
    * directory[/etc/chef/ohai/plugins] action create (skipped due to not_if)
    * cookbook_file[/etc/chef/ohai/plugins/aws.rb] action create (up to date)
    * ohai[aws] action reload
      - re-run ohai and merge results into node attributes

Recipe: chef-sugar::default
  * chef_gem[chef-sugar] action install (up to date)

  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/role-dse-aws-nativex/recipes/default.rb
  ================================================================================

  TypeError
  ---------
  false can't be coerced into Float

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/lvm/libraries/resource_lvm_logical_volume.rb:87:in `%'
    /var/chef/cache/cookbooks/lvm/libraries/resource_lvm_logical_volume.rb:87:in `block in stripe_size'
    /var/chef/cache/cookbooks/lvm/libraries/resource_lvm_logical_volume.rb:82:in `stripe_size'
    /var/chef/cache/cookbooks/ephemeral_lvm/recipes/default.rb:71:in `block (2 levels) in from_file'
    /var/chef/cache/cookbooks/lvm/libraries/resource_lvm_volume_group.rb:110:in `logical_volume'
    /var/chef/cache/cookbooks/ephemeral_lvm/recipes/default.rb:63:in `block in from_file'
    /var/chef/cache/cookbooks/ephemeral_lvm/recipes/default.rb:60:in `from_file'
    /var/chef/cache/cookbooks/ephemeral_lvm-nativex/recipes/default.rb:15:in `from_file'
    /var/chef/cache/cookbooks/role-base-linux-nativex/recipes/default.rb:172:in `from_file'
    /var/chef/cache/cookbooks/role-dse-aws-nativex/recipes/default.rb:96:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/lvm/libraries/resource_lvm_logical_volume.rb:

   80:        #
   81:        def stripe_size(arg = nil)
   82:          set_or_return(
   83:            :stripe_size,
   84:            arg,
   85:            kind_of: Integer,
   86:            callbacks: {
   87>>             'must be a power of 2' => proc { |value| Math.log2(value) % 1.zero? },
   88:            }
   89:          )
   90:        end
   91:
   92:        # Attribute: mirrors - number of mirrors for the volume
   93:        #
   94:        # @param arg [Integer] number of mirrors
   95:        #
   96:        # @return [Integer] number of mirrors

  Platform:
  ---------
  x86_64-linux

  Running handlers:
  Running handlers complete
  Chef Client failed. 2 resources updated in 06 seconds

### PR DESCRIPTION
**Pull request by Stromweld**
### Description

Fixes error "false can't be coerced into Float"

### Issues Resolved

#118 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by tas50** [comment]
Thanks

**Comment by Stromweld** [comment]
can this fix get pushed to the chef supermarket since the current version on the supermarket is broken?

**Comment by Stromweld** [comment]
@tas50 see previous question please ^^^^

**Comment by tas50** [comment]
4.0.5 shipped

**Comment by Stromweld** [comment]
thanks

**Pull request merged**
