### PR TITLE
Support thin pools and thin volumes

### LINKED ISSUE #70: support for -T (thin pool) option
Is there support for lvm -T option. I am unable to find info:

from man lvcreate:

-T, --thin, --thinpool ThinPoolLogicalVolume{Name|Path} Creates thin pool or thin logical volume or both. Specifying the optional argument --size will cause the creation of the thin pool logical volume. Specifying the optional argument --virtualsize will cause the creation of the thin logical volume from given thin pool volume. Specifying both arguments will cause the creation of both thin pool and thin volume using this pool. Requires device mapper kernel driver for thin provisioning from kernel 3.2 or newer.

### PR DESCRIPTION
**Pull request by keiths-osc**
### Description

Added `lvm_thin_pool` and `lvm_thin_volume` resources and associated tests.  See README.md for details about these new resources.

### Issues Resolved

#70

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by tas50** [comment]
ping Mr. LVM @irvingpop

**Comment by keiths-osc** [comment]
I noticed when running the kitchen tests locally that the resize-centos-511 suite fails.  However, it also fails with the exact same error when I run it at the v2.0.0 tag, so I don't think it is related to my changes.

**Comment by sjsadowski** [comment]
+1

**Comment by irvingpop** [comment]
This is super awesome!   One question:  Obviously `thin_pool` is a new thing that needs to be created within a VG.   Is it necessary to have a `thin_volume` resource that's separate from `logical_volume` rather than an argument  (e.g. `thin true`)

**Comment by keiths-osc** [comment]
Thanks @irvingpop!  That is a good question. As far as I could tell, a number of properties on a regular logical volume don't apply to thin volumes, and if you pass the corresponding arguments to `lvcreate` it actually causes an error.  The thin volume seemed like a more specialized version of a logical volume to me, so I made a resource structure that I felt matched and allowed for only having the appropriate properties while reusing as much code as possibile.  I could have done the `thin true` approach and then either 1) ignored any invalid properties, or 2) raised an error if any invalid properties were passed (which both would require some extra logic that my current approach doesn't need).  I could also do neither of those options (and if the user passes an invalid option, lvcreate would blow up).  To possibly help a user avoid doing that I could mention each option that is invalid with `thin true` in the readme, but I thought it might be better to have a specialized resource that doesn't even have the invalid options.

Here is an example of something that would be invalid that a user could do with the `thin true` approach:

```
lvm_logical_volume 'home' do
  thin true
  # some properties that do apply to thin volumes
  # ...

  # the following settings aren't valid for thin volumes but are options on the resource
  stripes     3
  mirrors     2
end
```

This same reasoning is mostly why I made the thin pool as a separate resource as well (though it is true that it is also an extra thing you have to create within the volume group).

**Comment by irvingpop** [comment]
That logic sounds totally sound to me.  Great contribution!  👍

**Comment by chrodriguez** [comment]
Forgot to upgrade version?

**Comment by tas50** [comment]
2.1.0 released

**Pull request merged**
